services:
  nestapi:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_db

